name: Cloud Function Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cloud_function_test:
    name: Cloud Function Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r function/requirements.txt
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - name: Cloud Function unit test
        run: python3 function/test_main.py